language: python

matrix:
  include:
    - python: 3.5
      env: TOXENV=py35 NO_TESTS_OVER_WIRE=1
    - python: 3.6
      env: TOXENV=py36 NO_TESTS_OVER_WIRE=1

install:
  - python -mpip install tox
script:
  - tox
after_success:
  - tox -e coveralls
