language: python
python:
  - "3.5"

install:
    - travis_retry python -mpip install tox==2.3.1
script:
    - tox -e py35
after_success:
    - tox -e py35-coveralls

# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false
